nohup bash -c '/usr/bin/time -v ./memrgc d -m genome -r HG17 -t HG18_ref_HG17_memrgc -o HG18_ref_HG17_dec' </dev/null 1> HG18_ref_HG17_memrgc_dec.out 2> HG18_ref_HG17_memrgc_dec.err
nohup bash -c '/usr/bin/time -v ./memrgc d -m genome -r HG17 -t HG19_ref_HG17_memrgc -o HG19_ref_HG17_dec' </dev/null 1> HG19_ref_HG17_memrgc_dec.out 2> HG19_ref_HG17_memrgc_dec.err
nohup bash -c '/usr/bin/time -v ./memrgc d -m genome -r HG17 -t HG38_ref_HG17_memrgc -o HG38_ref_HG17_dec' </dev/null 1> HG38_ref_HG17_memrgc_dec.out 2> HG38_ref_HG17_memrgc_dec.err
nohup bash -c '/usr/bin/time -v ./memrgc d -m genome -r HG17 -t YH_ref_HG17_memrgc -o YH_ref_HG17_dec' </dev/null 1> YH_ref_HG17_memrgc_dec.out 2> YH_ref_HG17_memrgc_dec.err
nohup bash -c '/usr/bin/time -v ./memrgc d -m genome -r HG17 -t KO131_ref_HG17_memrgc -o KO131_ref_HG17_dec' </dev/null 1> KO131_ref_HG17_memrgc_dec.out 2> KO131_ref_HG17_memrgc_dec.err
nohup bash -c '/usr/bin/time -v ./memrgc d -m genome -r HG17 -t KO224_ref_HG17_memrgc -o KO224_ref_HG17_dec' </dev/null 1> KO224_ref_HG17_memrgc_dec.out 2> KO224_ref_HG17_memrgc_dec.err
nohup bash -c '/usr/bin/time -v ./memrgc d -m genome -r HG17 -t HuRef_ref_HG17_memrgc -o HuRef_ref_HG17_dec' </dev/null 1> HuRef_ref_HG17_memrgc_dec.out 2> HuRef_ref_HG17_memrgc_dec.err
nohup bash -c '/usr/bin/time -v ./memrgc d -m genome -r HG18 -t HG17_ref_HG18_memrgc -o HG17_ref_HG18_dec' </dev/null 1> HG17_ref_HG18_memrgc_dec.out 2> HG17_ref_HG18_memrgc_dec.err
nohup bash -c '/usr/bin/time -v ./memrgc d -m genome -r HG18 -t HG19_ref_HG18_memrgc -o HG19_ref_HG18_dec' </dev/null 1> HG19_ref_HG18_memrgc_dec.out 2> HG19_ref_HG18_memrgc_dec.err
nohup bash -c '/usr/bin/time -v ./memrgc d -m genome -r HG18 -t HG38_ref_HG18_memrgc -o HG38_ref_HG18_dec' </dev/null 1> HG38_ref_HG18_memrgc_dec.out 2> HG38_ref_HG18_memrgc_dec.err
nohup bash -c '/usr/bin/time -v ./memrgc d -m genome -r HG18 -t YH_ref_HG18_memrgc -o YH_ref_HG18_dec' </dev/null 1> YH_ref_HG18_memrgc_dec.out 2> YH_ref_HG18_memrgc_dec.err
nohup bash -c '/usr/bin/time -v ./memrgc d -m genome -r HG18 -t KO131_ref_HG18_memrgc -o KO131_ref_HG18_dec' </dev/null 1> KO131_ref_HG18_memrgc_dec.out 2> KO131_ref_HG18_memrgc_dec.err
nohup bash -c '/usr/bin/time -v ./memrgc d -m genome -r HG18 -t KO224_ref_HG18_memrgc -o KO224_ref_HG18_dec' </dev/null 1> KO224_ref_HG18_memrgc_dec.out 2> KO224_ref_HG18_memrgc_dec.err
nohup bash -c '/usr/bin/time -v ./memrgc d -m genome -r HG18 -t HuRef_ref_HG18_memrgc -o HuRef_ref_HG18_dec' </dev/null 1> HuRef_ref_HG18_memrgc_dec.out 2> HuRef_ref_HG18_memrgc_dec.err
nohup bash -c '/usr/bin/time -v ./memrgc d -m genome -r HG19 -t HG17_ref_HG19_memrgc -o HG17_ref_HG19_dec' </dev/null 1> HG17_ref_HG19_memrgc_dec.out 2> HG17_ref_HG19_memrgc_dec.err
nohup bash -c '/usr/bin/time -v ./memrgc d -m genome -r HG19 -t HG18_ref_HG19_memrgc -o HG18_ref_HG19_dec' </dev/null 1> HG18_ref_HG19_memrgc_dec.out 2> HG18_ref_HG19_memrgc_dec.err
nohup bash -c '/usr/bin/time -v ./memrgc d -m genome -r HG19 -t HG38_ref_HG19_memrgc -o HG38_ref_HG19_dec' </dev/null 1> HG38_ref_HG19_memrgc_dec.out 2> HG38_ref_HG19_memrgc_dec.err
nohup bash -c '/usr/bin/time -v ./memrgc d -m genome -r HG19 -t YH_ref_HG19_memrgc -o YH_ref_HG19_dec' </dev/null 1> YH_ref_HG19_memrgc_dec.out 2> YH_ref_HG19_memrgc_dec.err
nohup bash -c '/usr/bin/time -v ./memrgc d -m genome -r HG19 -t KO131_ref_HG19_memrgc -o KO131_ref_HG19_dec' </dev/null 1> KO131_ref_HG19_memrgc_dec.out 2> KO131_ref_HG19_memrgc_dec.err
nohup bash -c '/usr/bin/time -v ./memrgc d -m genome -r HG19 -t KO224_ref_HG19_memrgc -o KO224_ref_HG19_dec' </dev/null 1> KO224_ref_HG19_memrgc_dec.out 2> KO224_ref_HG19_memrgc_dec.err
nohup bash -c '/usr/bin/time -v ./memrgc d -m genome -r HG19 -t HuRef_ref_HG19_memrgc -o HuRef_ref_HG19_dec' </dev/null 1> HuRef_ref_HG19_memrgc_dec.out 2> HuRef_ref_HG19_memrgc_dec.err
nohup bash -c '/usr/bin/time -v ./memrgc d -m genome -r HG38 -t HG17_ref_HG38_memrgc -o HG17_ref_HG38_dec' </dev/null 1> HG17_ref_HG38_memrgc_dec.out 2> HG17_ref_HG38_memrgc_dec.err
nohup bash -c '/usr/bin/time -v ./memrgc d -m genome -r HG38 -t HG18_ref_HG38_memrgc -o HG18_ref_HG38_dec' </dev/null 1> HG18_ref_HG38_memrgc_dec.out 2> HG18_ref_HG38_memrgc_dec.err
nohup bash -c '/usr/bin/time -v ./memrgc d -m genome -r HG38 -t HG19_ref_HG38_memrgc -o HG19_ref_HG38_dec' </dev/null 1> HG19_ref_HG38_memrgc_dec.out 2> HG19_ref_HG38_memrgc_dec.err
nohup bash -c '/usr/bin/time -v ./memrgc d -m genome -r HG38 -t YH_ref_HG38_memrgc -o YH_ref_HG38_dec' </dev/null 1> YH_ref_HG38_memrgc_dec.out 2> YH_ref_HG38_memrgc_dec.err
nohup bash -c '/usr/bin/time -v ./memrgc d -m genome -r HG38 -t KO131_ref_HG38_memrgc -o KO131_ref_HG38_dec' </dev/null 1> KO131_ref_HG38_memrgc_dec.out 2> KO131_ref_HG38_memrgc_dec.err
nohup bash -c '/usr/bin/time -v ./memrgc d -m genome -r HG38 -t KO224_ref_HG38_memrgc -o KO224_ref_HG38_dec' </dev/null 1> KO224_ref_HG38_memrgc_dec.out 2> KO224_ref_HG38_memrgc_dec.err
nohup bash -c '/usr/bin/time -v ./memrgc d -m genome -r HG38 -t HuRef_ref_HG38_memrgc -o HuRef_ref_HG38_dec' </dev/null 1> HuRef_ref_HG38_memrgc_dec.out 2> HuRef_ref_HG38_memrgc_dec.err
nohup bash -c '/usr/bin/time -v ./memrgc d -m genome -r YH -t HG17_ref_YH_memrgc -o HG17_ref_YH_dec' </dev/null 1> HG17_ref_YH_memrgc_dec.out 2> HG17_ref_YH_memrgc_dec.err
nohup bash -c '/usr/bin/time -v ./memrgc d -m genome -r YH -t HG18_ref_YH_memrgc -o HG18_ref_YH_dec' </dev/null 1> HG18_ref_YH_memrgc_dec.out 2> HG18_ref_YH_memrgc_dec.err
nohup bash -c '/usr/bin/time -v ./memrgc d -m genome -r YH -t HG19_ref_YH_memrgc -o HG19_ref_YH_dec' </dev/null 1> HG19_ref_YH_memrgc_dec.out 2> HG19_ref_YH_memrgc_dec.err
nohup bash -c '/usr/bin/time -v ./memrgc d -m genome -r YH -t HG38_ref_YH_memrgc -o HG38_ref_YH_dec' </dev/null 1> HG38_ref_YH_memrgc_dec.out 2> HG38_ref_YH_memrgc_dec.err
nohup bash -c '/usr/bin/time -v ./memrgc d -m genome -r YH -t KO131_ref_YH_memrgc -o KO131_ref_YH_dec' </dev/null 1> KO131_ref_YH_memrgc_dec.out 2> KO131_ref_YH_memrgc_dec.err
nohup bash -c '/usr/bin/time -v ./memrgc d -m genome -r YH -t KO224_ref_YH_memrgc -o KO224_ref_YH_dec' </dev/null 1> KO224_ref_YH_memrgc_dec.out 2> KO224_ref_YH_memrgc_dec.err
nohup bash -c '/usr/bin/time -v ./memrgc d -m genome -r YH -t HuRef_ref_YH_memrgc -o HuRef_ref_YH_dec' </dev/null 1> HuRef_ref_YH_memrgc_dec.out 2> HuRef_ref_YH_memrgc_dec.err
nohup bash -c '/usr/bin/time -v ./memrgc d -m genome -r KO131 -t HG17_ref_KO131_memrgc -o HG17_ref_KO131_dec' </dev/null 1> HG17_ref_KO131_memrgc_dec.out 2> HG17_ref_KO131_memrgc_dec.err
nohup bash -c '/usr/bin/time -v ./memrgc d -m genome -r KO131 -t HG18_ref_KO131_memrgc -o HG18_ref_KO131_dec' </dev/null 1> HG18_ref_KO131_memrgc_dec.out 2> HG18_ref_KO131_memrgc_dec.err
nohup bash -c '/usr/bin/time -v ./memrgc d -m genome -r KO131 -t HG19_ref_KO131_memrgc -o HG19_ref_KO131_dec' </dev/null 1> HG19_ref_KO131_memrgc_dec.out 2> HG19_ref_KO131_memrgc_dec.err
nohup bash -c '/usr/bin/time -v ./memrgc d -m genome -r KO131 -t HG38_ref_KO131_memrgc -o HG38_ref_KO131_dec' </dev/null 1> HG38_ref_KO131_memrgc_dec.out 2> HG38_ref_KO131_memrgc_dec.err
nohup bash -c '/usr/bin/time -v ./memrgc d -m genome -r KO131 -t YH_ref_KO131_memrgc -o YH_ref_KO131_dec' </dev/null 1> YH_ref_KO131_memrgc_dec.out 2> YH_ref_KO131_memrgc_dec.err
nohup bash -c '/usr/bin/time -v ./memrgc d -m genome -r KO131 -t KO224_ref_KO131_memrgc -o KO224_ref_KO131_dec' </dev/null 1> KO224_ref_KO131_memrgc_dec.out 2> KO224_ref_KO131_memrgc_dec.err
nohup bash -c '/usr/bin/time -v ./memrgc d -m genome -r KO131 -t HuRef_ref_KO131_memrgc -o HuRef_ref_KO131_dec' </dev/null 1> HuRef_ref_KO131_memrgc_dec.out 2> HuRef_ref_KO131_memrgc_dec.err
nohup bash -c '/usr/bin/time -v ./memrgc d -m genome -r KO224 -t HG17_ref_KO224_memrgc -o HG17_ref_KO224_dec' </dev/null 1> HG17_ref_KO224_memrgc_dec.out 2> HG17_ref_KO224_memrgc_dec.err
nohup bash -c '/usr/bin/time -v ./memrgc d -m genome -r KO224 -t HG18_ref_KO224_memrgc -o HG18_ref_KO224_dec' </dev/null 1> HG18_ref_KO224_memrgc_dec.out 2> HG18_ref_KO224_memrgc_dec.err
nohup bash -c '/usr/bin/time -v ./memrgc d -m genome -r KO224 -t HG19_ref_KO224_memrgc -o HG19_ref_KO224_dec' </dev/null 1> HG19_ref_KO224_memrgc_dec.out 2> HG19_ref_KO224_memrgc_dec.err
nohup bash -c '/usr/bin/time -v ./memrgc d -m genome -r KO224 -t HG38_ref_KO224_memrgc -o HG38_ref_KO224_dec' </dev/null 1> HG38_ref_KO224_memrgc_dec.out 2> HG38_ref_KO224_memrgc_dec.err
nohup bash -c '/usr/bin/time -v ./memrgc d -m genome -r KO224 -t YH_ref_KO224_memrgc -o YH_ref_KO224_dec' </dev/null 1> YH_ref_KO224_memrgc_dec.out 2> YH_ref_KO224_memrgc_dec.err
nohup bash -c '/usr/bin/time -v ./memrgc d -m genome -r KO224 -t KO131_ref_KO224_memrgc -o KO131_ref_KO224_dec' </dev/null 1> KO131_ref_KO224_memrgc_dec.out 2> KO131_ref_KO224_memrgc_dec.err
nohup bash -c '/usr/bin/time -v ./memrgc d -m genome -r KO224 -t HuRef_ref_KO224_memrgc -o HuRef_ref_KO224_dec' </dev/null 1> HuRef_ref_KO224_memrgc_dec.out 2> HuRef_ref_KO224_memrgc_dec.err
nohup bash -c '/usr/bin/time -v ./memrgc d -m genome -r HuRef -t HG17_ref_HuRef_memrgc -o HG17_ref_HuRef_dec' </dev/null 1> HG17_ref_HuRef_memrgc_dec.out 2> HG17_ref_HuRef_memrgc_dec.err
nohup bash -c '/usr/bin/time -v ./memrgc d -m genome -r HuRef -t HG18_ref_HuRef_memrgc -o HG18_ref_HuRef_dec' </dev/null 1> HG18_ref_HuRef_memrgc_dec.out 2> HG18_ref_HuRef_memrgc_dec.err
nohup bash -c '/usr/bin/time -v ./memrgc d -m genome -r HuRef -t HG19_ref_HuRef_memrgc -o HG19_ref_HuRef_dec' </dev/null 1> HG19_ref_HuRef_memrgc_dec.out 2> HG19_ref_HuRef_memrgc_dec.err
nohup bash -c '/usr/bin/time -v ./memrgc d -m genome -r HuRef -t HG38_ref_HuRef_memrgc -o HG38_ref_HuRef_dec' </dev/null 1> HG38_ref_HuRef_memrgc_dec.out 2> HG38_ref_HuRef_memrgc_dec.err
nohup bash -c '/usr/bin/time -v ./memrgc d -m genome -r HuRef -t YH_ref_HuRef_memrgc -o YH_ref_HuRef_dec' </dev/null 1> YH_ref_HuRef_memrgc_dec.out 2> YH_ref_HuRef_memrgc_dec.err
nohup bash -c '/usr/bin/time -v ./memrgc d -m genome -r HuRef -t KO131_ref_HuRef_memrgc -o KO131_ref_HuRef_dec' </dev/null 1> KO131_ref_HuRef_memrgc_dec.out 2> KO131_ref_HuRef_memrgc_dec.err
nohup bash -c '/usr/bin/time -v ./memrgc d -m genome -r HuRef -t KO224_ref_HuRef_memrgc -o KO224_ref_HuRef_dec' </dev/null 1> KO224_ref_HuRef_memrgc_dec.out 2> KO224_ref_HuRef_memrgc_dec.err
