nohup bash -c '/usr/bin/time -v ./hirgc -m genome -r HG17 -t HG18 -n default' </dev/null 1> HG18_ref_HG17.out 2> HG18_ref_HG17.err
nohup bash -c '/usr/bin/time -v ./hirgc -m genome -r HG17 -t HG19 -n default' </dev/null 1> HG19_ref_HG17.out 2> HG19_ref_HG17.err
nohup bash -c '/usr/bin/time -v ./hirgc -m genome -r HG17 -t HG38 -n default' </dev/null 1> HG38_ref_HG17.out 2> HG38_ref_HG17.err
nohup bash -c '/usr/bin/time -v ./hirgc -m genome -r HG17 -t YH -n default' </dev/null 1> YH_ref_HG17.out 2> YH_ref_HG17.err
nohup bash -c '/usr/bin/time -v ./hirgc -m genome -r HG17 -t KO131 -n default' </dev/null 1> KO131_ref_HG17.out 2> KO131_ref_HG17.err
nohup bash -c '/usr/bin/time -v ./hirgc -m genome -r HG17 -t KO224 -n default' </dev/null 1> KO224_ref_HG17.out 2> KO224_ref_HG17.err
nohup bash -c '/usr/bin/time -v ./hirgc -m genome -r HG17 -t HuRef -n default' </dev/null 1> HuRef_ref_HG17.out 2> HuRef_ref_HG17.err
nohup bash -c '/usr/bin/time -v ./hirgc -m genome -r HG18 -t HG17 -n default' </dev/null 1> HG17_ref_HG18.out 2> HG17_ref_HG18.err
nohup bash -c '/usr/bin/time -v ./hirgc -m genome -r HG18 -t HG19 -n default' </dev/null 1> HG19_ref_HG18.out 2> HG19_ref_HG18.err
nohup bash -c '/usr/bin/time -v ./hirgc -m genome -r HG18 -t HG38 -n default' </dev/null 1> HG38_ref_HG18.out 2> HG38_ref_HG18.err
nohup bash -c '/usr/bin/time -v ./hirgc -m genome -r HG18 -t YH -n default' </dev/null 1> YH_ref_HG18.out 2> YH_ref_HG18.err
nohup bash -c '/usr/bin/time -v ./hirgc -m genome -r HG18 -t KO131 -n default' </dev/null 1> KO131_ref_HG18.out 2> KO131_ref_HG18.err
nohup bash -c '/usr/bin/time -v ./hirgc -m genome -r HG18 -t KO224 -n default' </dev/null 1> KO224_ref_HG18.out 2> KO224_ref_HG18.err
nohup bash -c '/usr/bin/time -v ./hirgc -m genome -r HG18 -t HuRef -n default' </dev/null 1> HuRef_ref_HG18.out 2> HuRef_ref_HG18.err
nohup bash -c '/usr/bin/time -v ./hirgc -m genome -r HG19 -t HG17 -n default' </dev/null 1> HG17_ref_HG19.out 2> HG17_ref_HG19.err
nohup bash -c '/usr/bin/time -v ./hirgc -m genome -r HG19 -t HG18 -n default' </dev/null 1> HG18_ref_HG19.out 2> HG18_ref_HG19.err
nohup bash -c '/usr/bin/time -v ./hirgc -m genome -r HG19 -t HG38 -n default' </dev/null 1> HG38_ref_HG19.out 2> HG38_ref_HG19.err
nohup bash -c '/usr/bin/time -v ./hirgc -m genome -r HG19 -t YH -n default' </dev/null 1> YH_ref_HG19.out 2> YH_ref_HG19.err
nohup bash -c '/usr/bin/time -v ./hirgc -m genome -r HG19 -t KO131 -n default' </dev/null 1> KO131_ref_HG19.out 2> KO131_ref_HG19.err
nohup bash -c '/usr/bin/time -v ./hirgc -m genome -r HG19 -t KO224 -n default' </dev/null 1> KO224_ref_HG19.out 2> KO224_ref_HG19.err
nohup bash -c '/usr/bin/time -v ./hirgc -m genome -r HG19 -t HuRef -n default' </dev/null 1> HuRef_ref_HG19.out 2> HuRef_ref_HG19.err
nohup bash -c '/usr/bin/time -v ./hirgc -m genome -r HG38 -t HG17 -n default' </dev/null 1> HG17_ref_HG38.out 2> HG17_ref_HG38.err
nohup bash -c '/usr/bin/time -v ./hirgc -m genome -r HG38 -t HG18 -n default' </dev/null 1> HG18_ref_HG38.out 2> HG18_ref_HG38.err
nohup bash -c '/usr/bin/time -v ./hirgc -m genome -r HG38 -t HG19 -n default' </dev/null 1> HG19_ref_HG38.out 2> HG19_ref_HG38.err
nohup bash -c '/usr/bin/time -v ./hirgc -m genome -r HG38 -t YH -n default' </dev/null 1> YH_ref_HG38.out 2> YH_ref_HG38.err
nohup bash -c '/usr/bin/time -v ./hirgc -m genome -r HG38 -t KO131 -n default' </dev/null 1> KO131_ref_HG38.out 2> KO131_ref_HG38.err
nohup bash -c '/usr/bin/time -v ./hirgc -m genome -r HG38 -t KO224 -n default' </dev/null 1> KO224_ref_HG38.out 2> KO224_ref_HG38.err
nohup bash -c '/usr/bin/time -v ./hirgc -m genome -r HG38 -t HuRef -n default' </dev/null 1> HuRef_ref_HG38.out 2> HuRef_ref_HG38.err
nohup bash -c '/usr/bin/time -v ./hirgc -m genome -r YH -t HG17 -n default' </dev/null 1> HG17_ref_YH.out 2> HG17_ref_YH.err
nohup bash -c '/usr/bin/time -v ./hirgc -m genome -r YH -t HG18 -n default' </dev/null 1> HG18_ref_YH.out 2> HG18_ref_YH.err
nohup bash -c '/usr/bin/time -v ./hirgc -m genome -r YH -t HG19 -n default' </dev/null 1> HG19_ref_YH.out 2> HG19_ref_YH.err
nohup bash -c '/usr/bin/time -v ./hirgc -m genome -r YH -t HG38 -n default' </dev/null 1> HG38_ref_YH.out 2> HG38_ref_YH.err
nohup bash -c '/usr/bin/time -v ./hirgc -m genome -r YH -t KO131 -n default' </dev/null 1> KO131_ref_YH.out 2> KO131_ref_YH.err
nohup bash -c '/usr/bin/time -v ./hirgc -m genome -r YH -t KO224 -n default' </dev/null 1> KO224_ref_YH.out 2> KO224_ref_YH.err
nohup bash -c '/usr/bin/time -v ./hirgc -m genome -r YH -t HuRef -n default' </dev/null 1> HuRef_ref_YH.out 2> HuRef_ref_YH.err
nohup bash -c '/usr/bin/time -v ./hirgc -m genome -r KO131 -t HG17 -n default' </dev/null 1> HG17_ref_KO131.out 2> HG17_ref_KO131.err
nohup bash -c '/usr/bin/time -v ./hirgc -m genome -r KO131 -t HG18 -n default' </dev/null 1> HG18_ref_KO131.out 2> HG18_ref_KO131.err
nohup bash -c '/usr/bin/time -v ./hirgc -m genome -r KO131 -t HG19 -n default' </dev/null 1> HG19_ref_KO131.out 2> HG19_ref_KO131.err
nohup bash -c '/usr/bin/time -v ./hirgc -m genome -r KO131 -t HG38 -n default' </dev/null 1> HG38_ref_KO131.out 2> HG38_ref_KO131.err
nohup bash -c '/usr/bin/time -v ./hirgc -m genome -r KO131 -t YH -n default' </dev/null 1> YH_ref_KO131.out 2> YH_ref_KO131.err
nohup bash -c '/usr/bin/time -v ./hirgc -m genome -r KO131 -t KO224 -n default' </dev/null 1> KO224_ref_KO131.out 2> KO224_ref_KO131.err
nohup bash -c '/usr/bin/time -v ./hirgc -m genome -r KO131 -t HuRef -n default' </dev/null 1> HuRef_ref_KO131.out 2> HuRef_ref_KO131.err
nohup bash -c '/usr/bin/time -v ./hirgc -m genome -r KO224 -t HG17 -n default' </dev/null 1> HG17_ref_KO224.out 2> HG17_ref_KO224.err
nohup bash -c '/usr/bin/time -v ./hirgc -m genome -r KO224 -t HG18 -n default' </dev/null 1> HG18_ref_KO224.out 2> HG18_ref_KO224.err
nohup bash -c '/usr/bin/time -v ./hirgc -m genome -r KO224 -t HG19 -n default' </dev/null 1> HG19_ref_KO224.out 2> HG19_ref_KO224.err
nohup bash -c '/usr/bin/time -v ./hirgc -m genome -r KO224 -t HG38 -n default' </dev/null 1> HG38_ref_KO224.out 2> HG38_ref_KO224.err
nohup bash -c '/usr/bin/time -v ./hirgc -m genome -r KO224 -t YH -n default' </dev/null 1> YH_ref_KO224.out 2> YH_ref_KO224.err
nohup bash -c '/usr/bin/time -v ./hirgc -m genome -r KO224 -t KO131 -n default' </dev/null 1> KO131_ref_KO224.out 2> KO131_ref_KO224.err
nohup bash -c '/usr/bin/time -v ./hirgc -m genome -r KO224 -t HuRef -n default' </dev/null 1> HuRef_ref_KO224.out 2> HuRef_ref_KO224.err
nohup bash -c '/usr/bin/time -v ./hirgc -m genome -r HuRef -t HG17 -n default' </dev/null 1> HG17_ref_HuRef.out 2> HG17_ref_HuRef.err
nohup bash -c '/usr/bin/time -v ./hirgc -m genome -r HuRef -t HG18 -n default' </dev/null 1> HG18_ref_HuRef.out 2> HG18_ref_HuRef.err
nohup bash -c '/usr/bin/time -v ./hirgc -m genome -r HuRef -t HG19 -n default' </dev/null 1> HG19_ref_HuRef.out 2> HG19_ref_HuRef.err
nohup bash -c '/usr/bin/time -v ./hirgc -m genome -r HuRef -t HG38 -n default' </dev/null 1> HG38_ref_HuRef.out 2> HG38_ref_HuRef.err
nohup bash -c '/usr/bin/time -v ./hirgc -m genome -r HuRef -t YH -n default' </dev/null 1> YH_ref_HuRef.out 2> YH_ref_HuRef.err
nohup bash -c '/usr/bin/time -v ./hirgc -m genome -r HuRef -t KO131 -n default' </dev/null 1> KO131_ref_HuRef.out 2> KO131_ref_HuRef.err
nohup bash -c '/usr/bin/time -v ./hirgc -m genome -r HuRef -t KO224 -n default' </dev/null 1> KO224_ref_HuRef.out 2> KO224_ref_HuRef.err
